export interface Declaration2042Case {
  code: string;
  label: string;
  sectionId: string;
  /** id de l'élément (input/checkbox) DOM correspondant, pour y placer le focus depuis la recherche */
  elementId: string;
}

// Index de recherche des cases de la 2042. Doit être tenu à jour manuellement
// à chaque ajout de case dans un des formulaires (Menage, RevenusSalaires,
// GainsActionnariatSalarie, ...). `elementId` doit correspondre à l'id réel
// du champ dans le formulaire (id={`case-${code}`} pour les cases chiffrées,
// id dédié pour les cases à cocher du Ménage).
export const DECLARATION_2042_CASES: Declaration2042Case[] = [
  // Ménage — situations particulières
  { code: 'T', label: 'Je vis seul(e) avec au moins un enfant à ma charge', sectionId: 'menage', elementId: 'parent-isole' },
  { code: 'L', label: "J'ai élevé seul(e) un enfant pendant au moins 5 ans", sectionId: 'menage', elementId: 'ancien-parent-isole' },
  { code: 'P', label: "Vous êtes en situation d'invalidité", sectionId: 'menage', elementId: 'invalidite-declarant1' },
  { code: 'F', label: "Votre conjoint(e) est en situation d'invalidité", sectionId: 'menage', elementId: 'invalidite-declarant2' },
  { code: 'W', label: "Vous êtes ancien(ne) combattant(e) ou titulaire d'une pension militaire d'invalidité", sectionId: 'menage', elementId: 'ancien-combattant-declarant1' },
  { code: 'S', label: "Votre conjoint(e) est ancien(ne) combattant(e) ou titulaire d'une pension militaire d'invalidité", sectionId: 'menage', elementId: 'ancien-combattant-declarant2' },
  { code: 'W', label: "Vous êtes veuf/veuve d'un(e) ancien(ne) combattant(e) décédé(e) après 74 ans", sectionId: 'menage', elementId: 'veuf-ancien-combattant' },
  { code: 'G', label: 'Vous êtes titulaire d\'une pension de veuve de guerre', sectionId: 'menage', elementId: 'veuve-de-guerre' },

  // Traitements et salaires
  { code: '1AJ', label: 'Traitements et salaires — Déclarant 1', sectionId: 'salaires', elementId: 'case-1AJ' },
  { code: '1BJ', label: 'Traitements et salaires — Déclarant 2', sectionId: 'salaires', elementId: 'case-1BJ' },
  { code: '1AA', label: 'Revenus des salariés des particuliers employeurs — Déclarant 1', sectionId: 'salaires', elementId: 'case-1AA' },
  { code: '1BA', label: 'Revenus des salariés des particuliers employeurs — Déclarant 2', sectionId: 'salaires', elementId: 'case-1BA' },
  { code: '1GA', label: 'Abattement forfaitaire (assistants maternels/familiaux, journalistes) — Déclarant 1', sectionId: 'salaires', elementId: 'case-1GA' },
  { code: '1HA', label: 'Abattement forfaitaire (assistants maternels/familiaux, journalistes) — Déclarant 2', sectionId: 'salaires', elementId: 'case-1HA' },
  { code: '1GH', label: 'Heures supplémentaires et jours RTT exonérés — Déclarant 1', sectionId: 'salaires', elementId: 'case-1GH' },
  { code: '1HH', label: 'Heures supplémentaires et jours RTT exonérés — Déclarant 2', sectionId: 'salaires', elementId: 'case-1HH' },
  { code: '1PB', label: 'Pourboires exonérés — Déclarant 1', sectionId: 'salaires', elementId: 'case-1PB' },
  { code: '1PC', label: 'Pourboires exonérés — Déclarant 2', sectionId: 'salaires', elementId: 'case-1PC' },
  { code: '1AD', label: 'Primes de partage de la valeur exonérées (ex-prime Macron) — Déclarant 1', sectionId: 'salaires', elementId: 'case-1AD' },
  { code: '1BD', label: 'Primes de partage de la valeur exonérées (ex-prime Macron) — Déclarant 2', sectionId: 'salaires', elementId: 'case-1BD' },
  { code: '1AV', label: "Majoration du seuil d'exonération — Déclarant 1", sectionId: 'salaires', elementId: 'case-1AV' },
  { code: '1BV', label: "Majoration du seuil d'exonération — Déclarant 2", sectionId: 'salaires', elementId: 'case-1BV' },
  { code: '1GB', label: 'Revenus des associés et gérants (article 62 du CGI) — Déclarant 1', sectionId: 'salaires', elementId: 'case-1GB' },
  { code: '1HB', label: 'Revenus des associés et gérants (article 62 du CGI) — Déclarant 2', sectionId: 'salaires', elementId: 'case-1HB' },
  { code: '1GF', label: 'Droits d\'auteur, fonctionnaires chercheurs — Déclarant 1', sectionId: 'salaires', elementId: 'case-1GF' },
  { code: '1HF', label: 'Droits d\'auteur, fonctionnaires chercheurs — Déclarant 2', sectionId: 'salaires', elementId: 'case-1HF' },
  { code: '1GG', label: 'Agents généraux d\'assurance (salaires imposables) — Déclarant 1', sectionId: 'salaires', elementId: 'case-1GG' },
  { code: '1HG', label: 'Agents généraux d\'assurance (salaires imposables) — Déclarant 2', sectionId: 'salaires', elementId: 'case-1HG' },
  { code: '1AQ', label: 'Agents généraux d\'assurance (salaires exonérés) — Déclarant 1', sectionId: 'salaires', elementId: 'case-1AQ' },
  { code: '1BQ', label: 'Agents généraux d\'assurance (salaires exonérés) — Déclarant 2', sectionId: 'salaires', elementId: 'case-1BQ' },
  { code: '1PM', label: 'Indemnités pour préjudice moral (fraction > 1 M€) — Déclarant 1', sectionId: 'salaires', elementId: 'case-1PM' },
  { code: '1QM', label: 'Indemnités pour préjudice moral (fraction > 1 M€) — Déclarant 2', sectionId: 'salaires', elementId: 'case-1QM' },
  { code: '1DY', label: 'Salariés impatriés (salaires et primes exonérés) — Déclarant 1', sectionId: 'salaires', elementId: 'case-1DY' },
  { code: '1EY', label: 'Salariés impatriés (salaires et primes exonérés) — Déclarant 2', sectionId: 'salaires', elementId: 'case-1EY' },
  { code: '1SM', label: "Sommes exonérées provenant du CET — Déclarant 1", sectionId: 'salaires', elementId: 'case-1SM' },
  { code: '1DN', label: "Sommes exonérées provenant du CET — Déclarant 2", sectionId: 'salaires', elementId: 'case-1DN' },
  { code: '1GK', label: 'Ne perçoit plus de salaires 1GB, 1GF, 1GG, 1AG — Déclarant 1', sectionId: 'salaires', elementId: 'case-1GK' },
  { code: '1GL', label: 'Ne perçoit plus de salaires 1GB, 1GF, 1GG, 1AG — Déclarant 2', sectionId: 'salaires', elementId: 'case-1GL' },
  { code: '1AP', label: 'Autres revenus imposables (chômage, préretraite) — Déclarant 1', sectionId: 'salaires', elementId: 'case-1AP' },
  { code: '1BP', label: 'Autres revenus imposables (chômage, préretraite) — Déclarant 2', sectionId: 'salaires', elementId: 'case-1BP' },
  { code: '1AF', label: 'Salaires perçus par les non-résidents et salaires de source étrangère avec crédit d\'impôt — Déclarant 1', sectionId: 'salaires', elementId: 'case-1AF' },
  { code: '1BF', label: 'Salaires perçus par les non-résidents et salaires de source étrangère avec crédit d\'impôt — Déclarant 2', sectionId: 'salaires', elementId: 'case-1BF' },
  { code: '1AG', label: 'Autres salaires imposables de source étrangère — Déclarant 1', sectionId: 'salaires', elementId: 'case-1AG' },
  { code: '1BG', label: 'Autres salaires imposables de source étrangère — Déclarant 2', sectionId: 'salaires', elementId: 'case-1BG' },
  { code: '1AK', label: 'Frais réels — Déclarant 1', sectionId: 'salaires', elementId: 'case-1AK' },
  { code: '1BK', label: 'Frais réels — Déclarant 2', sectionId: 'salaires', elementId: 'case-1BK' },

  // Gains d'actionnariat salarié
  { code: '1TP', label: 'Rabais excédentaire sur options sur titres — Déclarant 1', sectionId: 'actionnariat', elementId: 'case-1TP' },
  { code: '1UP', label: 'Rabais excédentaire sur options sur titres — Déclarant 2', sectionId: 'actionnariat', elementId: 'case-1UP' },
  { code: '1TT', label: "Gains de levée d'options / actions gratuites attribuées à compter du 28.9.2012 — Déclarant 1", sectionId: 'actionnariat', elementId: 'case-1TT' },
  { code: '1UT', label: "Gains de levée d'options / actions gratuites attribuées à compter du 28.9.2012 — Déclarant 2", sectionId: 'actionnariat', elementId: 'case-1UT' },
  { code: '1TZ', label: 'Gain imposable après abattement (actions gratuites 8.8.2015-30.12.2016)', sectionId: 'actionnariat', elementId: 'case-1TZ' },
  { code: '1UZ', label: 'Abattement pour durée de détention (actions gratuites)', sectionId: 'actionnariat', elementId: 'case-1UZ' },
  { code: '1WZ', label: 'Abattement de 50 % (actions gratuites)', sectionId: 'actionnariat', elementId: 'case-1WZ' },
  { code: '1VZ', label: "Abattement fixe (départ à la retraite d'un dirigeant de PME)", sectionId: 'actionnariat', elementId: 'case-1VZ' },
  { code: '1NX', label: 'Gains et distributions de parts ou actions de carried-interest — Déclarant 1', sectionId: 'actionnariat', elementId: 'case-1NX' },
  { code: '1OX', label: 'Gains et distributions de parts ou actions de carried-interest — Déclarant 2', sectionId: 'actionnariat', elementId: 'case-1OX' },
  { code: '1NY', label: 'Carried-interest soumis à la contribution salariale de 30 % — Déclarant 1', sectionId: 'actionnariat', elementId: 'case-1NY' },
  { code: '1OY', label: 'Carried-interest soumis à la contribution salariale de 30 % — Déclarant 2', sectionId: 'actionnariat', elementId: 'case-1OY' },
  { code: '1AY', label: 'Bons de souscription de parts de créateur d\'entreprise (BSPCE) — Déclarant 1', sectionId: 'actionnariat', elementId: 'case-1AY' },
  { code: '1BY', label: 'Bons de souscription de parts de créateur d\'entreprise (BSPCE) — Déclarant 2', sectionId: 'actionnariat', elementId: 'case-1BY' },
  { code: '1MP', label: 'Management packages (gains de cession sur titres souscrits par salariés/dirigeants) — Déclarant 1', sectionId: 'actionnariat', elementId: 'case-1MP' },
  { code: '1MQ', label: 'Management packages (gains de cession sur titres souscrits par salariés/dirigeants) — Déclarant 2', sectionId: 'actionnariat', elementId: 'case-1MQ' },
  { code: '3VD', label: "Gains de levée d'options taxables à 18 % (attribuées avant le 28.9.2012)", sectionId: 'actionnariat', elementId: 'case-3VD' },
  { code: '3VI', label: "Gains de levée d'options taxables à 30 % (attribuées avant le 28.9.2012)", sectionId: 'actionnariat', elementId: 'case-3VI' },
  { code: '3VF', label: "Gains de levée d'options taxables à 41 % (attribuées avant le 28.9.2012)", sectionId: 'actionnariat', elementId: 'case-3VF' },
  { code: '3VJ', label: 'Gains imposables sur option, catégorie des salaires — Déclarant 1', sectionId: 'actionnariat', elementId: 'case-3VJ' },
  { code: '3VK', label: 'Gains imposables sur option, catégorie des salaires — Déclarant 2', sectionId: 'actionnariat', elementId: 'case-3VK' },
  { code: '3VN', label: 'Gains soumis à la contribution salariale de 10 %', sectionId: 'actionnariat', elementId: 'case-3VN' },
  { code: '0XX', label: 'Revenus exceptionnels ou différés à imposer selon le système du quotient', sectionId: 'actionnariat', elementId: 'case-0XX' },

  // Salaires et pensions exonérés retenus pour le calcul du taux effectif
  { code: '1AC', label: 'Salaires exonérés (taux effectif) — Déclarant 1', sectionId: 'taux-effectif', elementId: 'case-1AC' },
  { code: '1BC', label: 'Salaires exonérés (taux effectif) — Déclarant 2', sectionId: 'taux-effectif', elementId: 'case-1BC' },
  { code: '1GE', label: 'Marins-pêcheurs exerçant hors des eaux territoriales françaises — Déclarant 1', sectionId: 'taux-effectif', elementId: 'case-1GE' },
  { code: '1HE', label: 'Marins-pêcheurs exerçant hors des eaux territoriales françaises — Déclarant 2', sectionId: 'taux-effectif', elementId: 'case-1HE' },
  { code: '1AE', label: 'Frais réels (taux effectif) — Déclarant 1', sectionId: 'taux-effectif', elementId: 'case-1AE' },
  { code: '1BE', label: 'Frais réels (taux effectif) — Déclarant 2', sectionId: 'taux-effectif', elementId: 'case-1BE' },
  { code: '1AH', label: 'Pensions de source étrangère (taux effectif) — Déclarant 1', sectionId: 'taux-effectif', elementId: 'case-1AH' },
  { code: '1BH', label: 'Pensions de source étrangère (taux effectif) — Déclarant 2', sectionId: 'taux-effectif', elementId: 'case-1BH' },
  { code: 'RSE', label: 'Pays de provenance des revenus de source étrangère — Déclarant 1', sectionId: 'taux-effectif', elementId: 'case-RSE' },
  { code: 'RSF', label: 'Pays de provenance des revenus de source étrangère — Déclarant 2', sectionId: 'taux-effectif', elementId: 'case-RSF' },

  // Pensions, retraites et rentes
  { code: '1AS', label: 'Pensions, retraites et rentes — Déclarant 1', sectionId: 'pensions', elementId: 'case-1AS' },
  { code: '1BS', label: 'Pensions, retraites et rentes — Déclarant 2', sectionId: 'pensions', elementId: 'case-1BS' },
  { code: '1AT', label: 'Pensions de retraite en capital taxables à 7,5 % — Déclarant 1', sectionId: 'pensions', elementId: 'case-1AT' },
  { code: '1BT', label: 'Pensions de retraite en capital taxables à 7,5 % — Déclarant 2', sectionId: 'pensions', elementId: 'case-1BT' },
  { code: '1AI', label: "Pensions en capital des plans d'épargne retraite — Déclarant 1", sectionId: 'pensions', elementId: 'case-1AI' },
  { code: '1BI', label: "Pensions en capital des plans d'épargne retraite — Déclarant 2", sectionId: 'pensions', elementId: 'case-1BI' },
  { code: '1AZ', label: "Pensions d'invalidité — Déclarant 1", sectionId: 'pensions', elementId: 'case-1AZ' },
  { code: '1BZ', label: "Pensions d'invalidité — Déclarant 2", sectionId: 'pensions', elementId: 'case-1BZ' },
  { code: '1AO', label: 'Pensions alimentaires perçues — Déclarant 1', sectionId: 'pensions', elementId: 'case-1AO' },
  { code: '1BO', label: 'Pensions alimentaires perçues — Déclarant 2', sectionId: 'pensions', elementId: 'case-1BO' },
  { code: '1AL', label: 'Pensions non-résidents / source étrangère avec crédit d\'impôt — Déclarant 1', sectionId: 'pensions', elementId: 'case-1AL' },
  { code: '1BL', label: 'Pensions non-résidents / source étrangère avec crédit d\'impôt — Déclarant 2', sectionId: 'pensions', elementId: 'case-1BL' },
  { code: '1AM', label: 'Autres pensions imposables de source étrangère — Déclarant 1', sectionId: 'pensions', elementId: 'case-1AM' },
  { code: '1BM', label: 'Autres pensions imposables de source étrangère — Déclarant 2', sectionId: 'pensions', elementId: 'case-1BM' },
  { code: '1AW', label: 'Rentes viagères à titre onéreux perçues — Moins de 50 ans', sectionId: 'pensions', elementId: 'case-1AW' },
  { code: '1BW', label: 'Rentes viagères à titre onéreux perçues — De 50 à 59 ans', sectionId: 'pensions', elementId: 'case-1BW' },
  { code: '1CW', label: 'Rentes viagères à titre onéreux perçues — De 60 à 69 ans', sectionId: 'pensions', elementId: 'case-1CW' },
  { code: '1DW', label: 'Rentes viagères à titre onéreux perçues — À partir de 70 ans', sectionId: 'pensions', elementId: 'case-1DW' },
  { code: '1AR', label: 'Rentes viagères non-résidents/source étrangère avec crédit d\'impôt — Moins de 50 ans', sectionId: 'pensions', elementId: 'case-1AR' },
  { code: '1BR', label: 'Rentes viagères non-résidents/source étrangère avec crédit d\'impôt — De 50 à 59 ans', sectionId: 'pensions', elementId: 'case-1BR' },
  { code: '1CR', label: 'Rentes viagères non-résidents/source étrangère avec crédit d\'impôt — De 60 à 69 ans', sectionId: 'pensions', elementId: 'case-1CR' },
  { code: '1DR', label: 'Rentes viagères non-résidents/source étrangère avec crédit d\'impôt — À partir de 70 ans', sectionId: 'pensions', elementId: 'case-1DR' },
  { code: '1HK', label: 'Ne perçoit plus de pensions 1AO, 1AM — Déclarant 1', sectionId: 'pensions', elementId: 'case-1HK' },
  { code: '1HL', label: 'Ne perçoit plus de pensions 1AO, 1AM — Déclarant 2', sectionId: 'pensions', elementId: 'case-1HL' },

  // Revenus des valeurs et capitaux mobiliers
  { code: '2DH', label: "Contrats d'assurance-vie ≥ 8 ans, produits soumis au prélèvement libératoire", sectionId: 'capitaux-mobiliers', elementId: 'case-2DH' },
  { code: '2CH', label: "Contrats d'assurance-vie ≥ 8 ans, autres produits", sectionId: 'capitaux-mobiliers', elementId: 'case-2CH' },
  { code: '2UU', label: "Contrats d'assurance-vie ≥ 8 ans, total perçu à répartir", sectionId: 'capitaux-mobiliers', elementId: 'case-2UU' },
  { code: '2VV', label: "Contrats d'assurance-vie ≥ 8 ans, produits imposables à 7,5 %", sectionId: 'capitaux-mobiliers', elementId: 'case-2VV' },
  { code: '2WW', label: "Contrats d'assurance-vie ≥ 8 ans, produits imposables à 12,8 %", sectionId: 'capitaux-mobiliers', elementId: 'case-2WW' },
  { code: '2XX', label: "Contrats d'assurance-vie < 8 ans, produits soumis au prélèvement libératoire", sectionId: 'capitaux-mobiliers', elementId: 'case-2XX' },
  { code: '2YY', label: "Contrats d'assurance-vie < 8 ans, autres produits", sectionId: 'capitaux-mobiliers', elementId: 'case-2YY' },
  { code: '2ZZ', label: "Contrats d'assurance-vie < 8 ans, produits versements après 27.9.2017", sectionId: 'capitaux-mobiliers', elementId: 'case-2ZZ' },
  { code: '2DC', label: 'Revenus des actions et parts (abattement 40 % si option barème)', sectionId: 'capitaux-mobiliers', elementId: 'case-2DC' },
  { code: '2FU', label: 'Dividendes imposables des titres non cotés (PEA/PEA-PME)', sectionId: 'capitaux-mobiliers', elementId: 'case-2FU' },
  { code: '2TR', label: 'Intérêts et autres produits de placement à revenu fixe', sectionId: 'capitaux-mobiliers', elementId: 'case-2TR' },
  { code: '2TT', label: 'Intérêts des prêts participatifs et des minibons', sectionId: 'capitaux-mobiliers', elementId: 'case-2TT' },
  { code: '2TQ', label: 'Intérêts imposables des obligations remboursables en actions (PEA-PME)', sectionId: 'capitaux-mobiliers', elementId: 'case-2TQ' },
  { code: '2TS', label: 'Autres revenus distribués et assimilés', sectionId: 'capitaux-mobiliers', elementId: 'case-2TS' },
  { code: '2TZ', label: "Produits des plans d'épargne retraite, sortie en capital", sectionId: 'capitaux-mobiliers', elementId: 'case-2TZ' },
  { code: '2GO', label: 'Revenus réputés distribués et structures hors de France à régime fiscal privilégié', sectionId: 'capitaux-mobiliers', elementId: 'case-2GO' },
  { code: '2TU', label: 'Pertes prêts participatifs/minibons non imputées, provenant de 2021', sectionId: 'capitaux-mobiliers', elementId: 'case-2TU' },
  { code: '2TV', label: 'Pertes prêts participatifs/minibons non imputées, provenant de 2022', sectionId: 'capitaux-mobiliers', elementId: 'case-2TV' },
  { code: '2TW', label: 'Pertes prêts participatifs/minibons non imputées, provenant de 2023', sectionId: 'capitaux-mobiliers', elementId: 'case-2TW' },
  { code: '2TX', label: 'Pertes prêts participatifs/minibons non imputées, provenant de 2024', sectionId: 'capitaux-mobiliers', elementId: 'case-2TX' },
  { code: '2TY', label: 'Pertes prêts participatifs/minibons non imputées, provenant de 2025', sectionId: 'capitaux-mobiliers', elementId: 'case-2TY' },
  { code: '2CG', label: 'Revenus déjà soumis aux prélèvements sociaux, sans CSG déductible', sectionId: 'capitaux-mobiliers', elementId: 'case-2CG' },
  { code: '2BH', label: 'Revenus déjà soumis aux prélèvements sociaux, avec CSG déductible si option barème', sectionId: 'capitaux-mobiliers', elementId: 'case-2BH' },
  { code: '2DF', label: 'Autres revenus déjà soumis aux prélèvements sociaux avec CSG déductible', sectionId: 'capitaux-mobiliers', elementId: 'case-2DF' },
  { code: '2DG', label: 'Revenus soumis au seul prélèvement de solidarité de 7,5 %', sectionId: 'capitaux-mobiliers', elementId: 'case-2DG' },
  { code: '2DI', label: 'Revenus soumis au seul prélèvement de solidarité, CSG/CRDS', sectionId: 'capitaux-mobiliers', elementId: 'case-2DI' },
  { code: '2CA', label: 'Frais et charges déductibles si option barème', sectionId: 'capitaux-mobiliers', elementId: 'case-2CA' },
  { code: '2AB', label: 'Crédits d\'impôt sur valeurs étrangères', sectionId: 'capitaux-mobiliers', elementId: 'case-2AB' },
  { code: '2CK', label: 'Prélèvement forfaitaire non libératoire déjà versé', sectionId: 'capitaux-mobiliers', elementId: 'case-2CK' },
  { code: '2EE', label: 'Autres revenus soumis à un prélèvement ou une retenue libératoire', sectionId: 'capitaux-mobiliers', elementId: 'case-2EE' },
  { code: '2AA', label: 'Déficits années antérieures non déduits, provenant de 2019', sectionId: 'capitaux-mobiliers', elementId: 'case-2AA' },
  { code: '2AL', label: 'Déficits années antérieures non déduits, provenant de 2020', sectionId: 'capitaux-mobiliers', elementId: 'case-2AL' },
  { code: '2AM', label: 'Déficits années antérieures non déduits, provenant de 2021', sectionId: 'capitaux-mobiliers', elementId: 'case-2AM' },
  { code: '2AN', label: 'Déficits années antérieures non déduits, provenant de 2022', sectionId: 'capitaux-mobiliers', elementId: 'case-2AN' },
  { code: '2AQ', label: 'Déficits années antérieures non déduits, provenant de 2023', sectionId: 'capitaux-mobiliers', elementId: 'case-2AQ' },
  { code: '2AR', label: 'Déficits années antérieures non déduits, provenant de 2024', sectionId: 'capitaux-mobiliers', elementId: 'case-2AR' },
  { code: '2VM', label: 'Gains de cession bons/contrats, soumis au prélèvement libératoire', sectionId: 'capitaux-mobiliers', elementId: 'case-2VM' },
  { code: '2VN', label: 'Gains de cession bons/contrats, autres gains', sectionId: 'capitaux-mobiliers', elementId: 'case-2VN' },
  { code: '2VO', label: 'Gains de cession bons/contrats, imposables à 7,5 %', sectionId: 'capitaux-mobiliers', elementId: 'case-2VO' },
  { code: '2VP', label: 'Gains de cession bons/contrats, imposables à 12,8 %', sectionId: 'capitaux-mobiliers', elementId: 'case-2VP' },
  { code: '2VQ', label: 'Moins-values de cession non imputées à reporter, provenant de 2021', sectionId: 'capitaux-mobiliers', elementId: 'case-2VQ' },
  { code: '2VR', label: 'Moins-values de cession non imputées à reporter, provenant de 2022', sectionId: 'capitaux-mobiliers', elementId: 'case-2VR' },
  { code: '2VS', label: 'Moins-values de cession non imputées à reporter, provenant de 2023', sectionId: 'capitaux-mobiliers', elementId: 'case-2VS' },
  { code: '2VT', label: 'Moins-values de cession non imputées à reporter, provenant de 2024', sectionId: 'capitaux-mobiliers', elementId: 'case-2VT' },
  { code: '2VU', label: 'Moins-values de cession non imputées à reporter, provenant de 2025', sectionId: 'capitaux-mobiliers', elementId: 'case-2VU' },
  { code: '2OP', label: 'Option pour l\'imposition au barème des revenus de capitaux mobiliers', sectionId: 'capitaux-mobiliers', elementId: 'case-2OP' },
];
