// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://npypkocowjkszxtecxzq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5weXBrb2Nvd2prc3p4dGVjeHpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyOTI2NDYsImV4cCI6MjA2OTg2ODY0Nn0.1N3fZw-_TuwpS3WhgKrTzN_kfSf_iPNhvFm7lnQnfsk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});